/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _agentRuns_mutations from "../_agentRuns/mutations.js";
import type * as _agentRuns_queries from "../_agentRuns/queries.js";
import type * as _agentTasks_chatPrompt from "../_agentTasks/chatPrompt.js";
import type * as _agentTasks_drafts from "../_agentTasks/drafts.js";
import type * as _agentTasks_execution from "../_agentTasks/execution.js";
import type * as _agentTasks_helpers from "../_agentTasks/helpers.js";
import type * as _agentTasks_internal from "../_agentTasks/internal.js";
import type * as _agentTasks_mutations from "../_agentTasks/mutations.js";
import type * as _agentTasks_queries from "../_agentTasks/queries.js";
import type * as _agentTasks_runSummary from "../_agentTasks/runSummary.js";
import type * as _agentTasks_sandbox from "../_agentTasks/sandbox.js";
import type * as _auth_currentUser from "../_auth/currentUser.js";
import type * as _auth_experimentalFlags from "../_auth/experimentalFlags.js";
import type * as _automationWorkflow_deliverable from "../_automationWorkflow/deliverable.js";
import type * as _automationWorkflow_findings from "../_automationWorkflow/findings.js";
import type * as _automationWorkflow_prompts from "../_automationWorkflow/prompts.js";
import type * as _automations_crud from "../_automations/crud.js";
import type * as _automations_findings from "../_automations/findings.js";
import type * as _automations_helpers from "../_automations/helpers.js";
import type * as _automations_prompts_addTestCoverage from "../_automations/prompts/addTestCoverage.js";
import type * as _automations_prompts_dailyStandup from "../_automations/prompts/dailyStandup.js";
import type * as _automations_prompts_findCriticalBugs from "../_automations/prompts/findCriticalBugs.js";
import type * as _automations_prompts_generateDocs from "../_automations/prompts/generateDocs.js";
import type * as _automations_prompts_improveCodeStructure from "../_automations/prompts/improveCodeStructure.js";
import type * as _automations_prompts_thermoNuclearCodeReview from "../_automations/prompts/thermoNuclearCodeReview.js";
import type * as _automations_runs from "../_automations/runs.js";
import type * as _automations_systemAutomations from "../_automations/systemAutomations.js";
import type * as _automations_systemInstall from "../_automations/systemInstall.js";
import type * as _automations_triggers from "../_automations/triggers.js";
import type * as _chat_cancelledMessage from "../_chat/cancelledMessage.js";
import type * as _chat_chatResult from "../_chat/chatResult.js";
import type * as _chat_daemonClaimPause from "../_chat/daemonClaimPause.js";
import type * as _chat_pendingTurnRestage from "../_chat/pendingTurnRestage.js";
import type * as _chat_projectChatDaemon from "../_chat/projectChatDaemon.js";
import type * as _chat_stallRetry from "../_chat/stallRetry.js";
import type * as _chat_stallWatchdog from "../_chat/stallWatchdog.js";
import type * as _chat_storageUrls from "../_chat/storageUrls.js";
import type * as _chat_surfaceAdapters from "../_chat/surfaceAdapters.js";
import type * as _chat_taskChatDaemon from "../_chat/taskChatDaemon.js";
import type * as _chat_turnLease from "../_chat/turnLease.js";
import type * as _chat_turnProjection from "../_chat/turnProjection.js";
import type * as _chat_turnStore from "../_chat/turnStore.js";
import type * as _deployment_vercel from "../_deployment/vercel.js";
import type * as _docEditor_markdown from "../_docEditor/markdown.js";
import type * as _drafts_helpers from "../_drafts/helpers.js";
import type * as _drafts_mutations from "../_drafts/mutations.js";
import type * as _drafts_queries from "../_drafts/queries.js";
import type * as _env_publicConvexUrls from "../_env/publicConvexUrls.js";
import type * as _envVars_listDisplay from "../_envVars/listDisplay.js";
import type * as _envVars_vercelCredentials from "../_envVars/vercelCredentials.js";
import type * as _git_branchNames from "../_git/branchNames.js";
import type * as _git_remoteRef from "../_git/remoteRef.js";
import type * as _github_api from "../_github/api.js";
import type * as _github_authErrors from "../_github/authErrors.js";
import type * as _github_deploymentSnapshot from "../_github/deploymentSnapshot.js";
import type * as _github_evaPrOwnership from "../_github/evaPrOwnership.js";
import type * as _github_helpers from "../_github/helpers.js";
import type * as _github_prComments from "../_github/prComments.js";
import type * as _github_prDescription from "../_github/prDescription.js";
import type * as _github_prDescriptionPrompt from "../_github/prDescriptionPrompt.js";
import type * as _github_prDiff from "../_github/prDiff.js";
import type * as _github_prDiffFallback from "../_github/prDiffFallback.js";
import type * as _github_prErrors from "../_github/prErrors.js";
import type * as _github_prFlow from "../_github/prFlow.js";
import type * as _github_prMeta from "../_github/prMeta.js";
import type * as _github_prOverview from "../_github/prOverview.js";
import type * as _github_prRecapService from "../_github/prRecapService.js";
import type * as _github_prReview from "../_github/prReview.js";
import type * as _github_prTitleSync from "../_github/prTitleSync.js";
import type * as _github_pullRequests from "../_github/pullRequests.js";
import type * as _github_sessionMergeGuard from "../_github/sessionMergeGuard.js";
import type * as _github_sync from "../_github/sync.js";
import type * as _github_userAuth from "../_github/userAuth.js";
import type * as _github_userTokens from "../_github/userTokens.js";
import type * as _githubRepos_helpers from "../_githubRepos/helpers.js";
import type * as _githubRepos_mutations from "../_githubRepos/mutations.js";
import type * as _githubRepos_queries from "../_githubRepos/queries.js";
import type * as _githubRepos_sandboxRepoPick from "../_githubRepos/sandboxRepoPick.js";
import type * as _githubRepos_sync from "../_githubRepos/sync.js";
import type * as _harnessSkills_filter from "../_harnessSkills/filter.js";
import type * as _harnessSkills_report from "../_harnessSkills/report.js";
import type * as _logs_resolveProjectId from "../_logs/resolveProjectId.js";
import type * as _logs_usage from "../_logs/usage.js";
import type * as _logs_usageSummary from "../_logs/usageSummary.js";
import type * as _mcp_redirectUri from "../_mcp/redirectUri.js";
import type * as _mentions_dataKinds from "../_mentions/dataKinds.js";
import type * as _mentions_extractMentionedUserIds from "../_mentions/extractMentionedUserIds.js";
import type * as _mentions_listData from "../_mentions/listData.js";
import type * as _mentions_mentionToken from "../_mentions/mentionToken.js";
import type * as _mentions_notifyChatMentions from "../_mentions/notifyChatMentions.js";
import type * as _mentions_resolveDocMentions from "../_mentions/resolveDocMentions.js";
import type * as _mentions_resolveMessageTokens from "../_mentions/resolveMessageTokens.js";
import type * as _mentions_resolveSkillMentions from "../_mentions/resolveSkillMentions.js";
import type * as _mentions_skillToken from "../_mentions/skillToken.js";
import type * as _messages_media from "../_messages/media.js";
import type * as _messages_preview from "../_messages/preview.js";
import type * as _migrations_backfillArchivedFromPrState from "../_migrations/backfillArchivedFromPrState.js";
import type * as _migrations_backfillEvaPrRecapOrigin from "../_migrations/backfillEvaPrRecapOrigin.js";
import type * as _migrations_backfillExperimentalFlags from "../_migrations/backfillExperimentalFlags.js";
import type * as _migrations_backfillNumIds from "../_migrations/backfillNumIds.js";
import type * as _migrations_backfillQueuedMessageOrder from "../_migrations/backfillQueuedMessageOrder.js";
import type * as _migrations_backfillTaskSubscribers from "../_migrations/backfillTaskSubscribers.js";
import type * as _migrations_cleanup from "../_migrations/cleanup.js";
import type * as _migrations_deleteRepos from "../_migrations/deleteRepos.js";
import type * as _migrations_deploymentUrl from "../_migrations/deploymentUrl.js";
import type * as _migrations_excludeConvexUrlFromSandbox from "../_migrations/excludeConvexUrlFromSandbox.js";
import type * as _migrations_logProjectIds from "../_migrations/logProjectIds.js";
import type * as _migrations_projectInterview from "../_migrations/projectInterview.js";
import type * as _migrations_projectPhases from "../_migrations/projectPhases.js";
import type * as _migrations_removeProjectIdField from "../_migrations/removeProjectIdField.js";
import type * as _migrations_removeSessionStartupRequestedAt from "../_migrations/removeSessionStartupRequestedAt.js";
import type * as _migrations_removeSnapshotWarmupFields from "../_migrations/removeSnapshotWarmupFields.js";
import type * as _migrations_repoSkills from "../_migrations/repoSkills.js";
import type * as _prRecapWorkflow_finalizeOutcome from "../_prRecapWorkflow/finalizeOutcome.js";
import type * as _prRecapWorkflow_prompts from "../_prRecapWorkflow/prompts.js";
import type * as _prRecapWorkflow_recapState from "../_prRecapWorkflow/recapState.js";
import type * as _prRecapWorkflow_staleDoc from "../_prRecapWorkflow/staleDoc.js";
import type * as _prRecapWorkflow_start from "../_prRecapWorkflow/start.js";
import type * as _projects_chatPrompt from "../_projects/chatPrompt.js";
import type * as _projects_development from "../_projects/development.js";
import type * as _projects_helpers from "../_projects/helpers.js";
import type * as _projects_internal from "../_projects/internal.js";
import type * as _projects_mutations from "../_projects/mutations.js";
import type * as _projects_prSync from "../_projects/prSync.js";
import type * as _projects_queries from "../_projects/queries.js";
import type * as _projects_sandbox from "../_projects/sandbox.js";
import type * as _pty_launchDevServerInVercelConsole from "../_pty/launchDevServerInVercelConsole.js";
import type * as _pty_owners from "../_pty/owners.js";
import type * as _pty_vercel from "../_pty/vercel.js";
import type * as _queues_helpers from "../_queues/helpers.js";
import type * as _repoSkills_content from "../_repoSkills/content.js";
import type * as _repoSkills_decodeGitHubContent from "../_repoSkills/decodeGitHubContent.js";
import type * as _repoSkills_skillMarkdown from "../_repoSkills/skillMarkdown.js";
import type * as _repoSkills_sync from "../_repoSkills/sync.js";
import type * as _repoSnapshots_builds from "../_repoSnapshots/builds.js";
import type * as _repoSnapshots_config from "../_repoSnapshots/config.js";
import type * as _repoSnapshots_repoMetadata from "../_repoSnapshots/repoMetadata.js";
import type * as _repoSnapshots_sanitizeSeededApps from "../_repoSnapshots/sanitizeSeededApps.js";
import type * as _sandbox_factory from "../_sandbox/factory.js";
import type * as _sandbox_ffmpegInstall from "../_sandbox/ffmpegInstall.js";
import type * as _sandbox_owner from "../_sandbox/owner.js";
import type * as _sandbox_provider from "../_sandbox/provider.js";
import type * as _sandbox_resolveExistingSandboxId from "../_sandbox/resolveExistingSandboxId.js";
import type * as _sandbox_startupActivity from "../_sandbox/startupActivity.js";
import type * as _sandbox_stickyPreview from "../_sandbox/stickyPreview.js";
import type * as _sandbox_stopRecovery from "../_sandbox/stopRecovery.js";
import type * as _sandbox_tags from "../_sandbox/tags.js";
import type * as _sandbox_vercelEnvFile from "../_sandbox/vercelEnvFile.js";
import type * as _sandbox_vercelProvider from "../_sandbox/vercelProvider.js";
import type * as _sandbox_vercelSnapshotOptions from "../_sandbox/vercelSnapshotOptions.js";
import type * as _sandbox_runtime_attachments from "../_sandbox_runtime/attachments.js";
import type * as _sandbox_runtime_backgroundProcesses from "../_sandbox_runtime/backgroundProcesses.js";
import type * as _sandbox_runtime_bulkSnapshotRetention from "../_sandbox_runtime/bulkSnapshotRetention.js";
import type * as _sandbox_runtime_callbackAuth from "../_sandbox_runtime/callbackAuth.js";
import type * as _sandbox_runtime_callbackScript from "../_sandbox_runtime/callbackScript.js";
import type * as _sandbox_runtime_callbackScriptFingerprint from "../_sandbox_runtime/callbackScriptFingerprint.js";
import type * as _sandbox_runtime_claudeCliVersion from "../_sandbox_runtime/claudeCliVersion.js";
import type * as _sandbox_runtime_convexLocalBackend from "../_sandbox_runtime/convexLocalBackend.js";
import type * as _sandbox_runtime_daemonEntitySnapshot from "../_sandbox_runtime/daemonEntitySnapshot.js";
import type * as _sandbox_runtime_daemonPaths from "../_sandbox_runtime/daemonPaths.js";
import type * as _sandbox_runtime_desktop from "../_sandbox_runtime/desktop.js";
import type * as _sandbox_runtime_devServer from "../_sandbox_runtime/devServer.js";
import type * as _sandbox_runtime_divergedPublish from "../_sandbox_runtime/divergedPublish.js";
import type * as _sandbox_runtime_execution from "../_sandbox_runtime/execution.js";
import type * as _sandbox_runtime_git from "../_sandbox_runtime/git.js";
import type * as _sandbox_runtime_gitCredentials from "../_sandbox_runtime/gitCredentials.js";
import type * as _sandbox_runtime_gitRemoteCommand from "../_sandbox_runtime/gitRemoteCommand.js";
import type * as _sandbox_runtime_helpers from "../_sandbox_runtime/helpers.js";
import type * as _sandbox_runtime_httpReadyProbe from "../_sandbox_runtime/httpReadyProbe.js";
import type * as _sandbox_runtime_launch from "../_sandbox_runtime/launch.js";
import type * as _sandbox_runtime_lifecycle from "../_sandbox_runtime/lifecycle.js";
import type * as _sandbox_runtime_prepareSandboxSteps from "../_sandbox_runtime/prepareSandboxSteps.js";
import type * as _sandbox_runtime_previewProxy from "../_sandbox_runtime/previewProxy.js";
import type * as _sandbox_runtime_previewRecovery from "../_sandbox_runtime/previewRecovery.js";
import type * as _sandbox_runtime_resumeSandboxSteps from "../_sandbox_runtime/resumeSandboxSteps.js";
import type * as _sandbox_runtime_runDevServer from "../_sandbox_runtime/runDevServer.js";
import type * as _sandbox_runtime_sandboxErrors from "../_sandbox_runtime/sandboxErrors.js";
import type * as _sandbox_runtime_sandboxFiles from "../_sandbox_runtime/sandboxFiles.js";
import type * as _sandbox_runtime_services from "../_sandbox_runtime/services.js";
import type * as _sandbox_runtime_sessions from "../_sandbox_runtime/sessions.js";
import type * as _sandbox_runtime_snapshotStates from "../_sandbox_runtime/snapshotStates.js";
import type * as _sandbox_runtime_swap from "../_sandbox_runtime/swap.js";
import type * as _sandbox_runtime_turnRevert from "../_sandbox_runtime/turnRevert.js";
import type * as _sandbox_runtime_vercelAppPorts from "../_sandbox_runtime/vercelAppPorts.js";
import type * as _sessions_backgroundAgents from "../_sessions/backgroundAgents.js";
import type * as _sessions_baseBranch from "../_sessions/baseBranch.js";
import type * as _sessions_daemonState from "../_sessions/daemonState.js";
import type * as _sessions_execution from "../_sessions/execution.js";
import type * as _sessions_helpers from "../_sessions/helpers.js";
import type * as _sessions_internal from "../_sessions/internal.js";
import type * as _sessions_mutations from "../_sessions/mutations.js";
import type * as _sessions_orchestrator from "../_sessions/orchestrator.js";
import type * as _sessions_pendingTurnRecovery from "../_sessions/pendingTurnRecovery.js";
import type * as _sessions_prArchive from "../_sessions/prArchive.js";
import type * as _sessions_prompts from "../_sessions/prompts.js";
import type * as _sessions_proposedPlans from "../_sessions/proposedPlans.js";
import type * as _sessions_pty from "../_sessions/pty.js";
import type * as _sessions_queries from "../_sessions/queries.js";
import type * as _sessions_resultTarget from "../_sessions/resultTarget.js";
import type * as _sessions_sandbox from "../_sessions/sandbox.js";
import type * as _sessions_workflow from "../_sessions/workflow.js";
import type * as _shared_commentAnchor from "../_shared/commentAnchor.js";
import type * as _shared_modelHandoff from "../_shared/modelHandoff.js";
import type * as _systemSkills_evaAsk from "../_systemSkills/evaAsk.js";
import type * as _systemSkills_evaAudit from "../_systemSkills/evaAudit.js";
import type * as _systemSkills_evaCapture from "../_systemSkills/evaCapture.js";
import type * as _systemSkills_evaDesign from "../_systemSkills/evaDesign.js";
import type * as _systemSkills_evaOrchestrator from "../_systemSkills/evaOrchestrator.js";
import type * as _systemSkills_evaPlan from "../_systemSkills/evaPlan.js";
import type * as _systemSkills_registry from "../_systemSkills/registry.js";
import type * as _taskWorkflow_deploymentHelpers from "../_taskWorkflow/deploymentHelpers.js";
import type * as _taskWorkflow_events from "../_taskWorkflow/events.js";
import type * as _taskWorkflow_helpers from "../_taskWorkflow/helpers.js";
import type * as _taskWorkflow_livenessProbe from "../_taskWorkflow/livenessProbe.js";
import type * as _taskWorkflow_prompts from "../_taskWorkflow/prompts.js";
import type * as _taskWorkflow_publicMutations from "../_taskWorkflow/publicMutations.js";
import type * as _taskWorkflow_queries from "../_taskWorkflow/queries.js";
import type * as _taskWorkflow_recovery from "../_taskWorkflow/recovery.js";
import type * as _taskWorkflow_resolveBaseBranch from "../_taskWorkflow/resolveBaseBranch.js";
import type * as _taskWorkflow_runLifecycle from "../_taskWorkflow/runLifecycle.js";
import type * as _taskWorkflow_scheduling from "../_taskWorkflow/scheduling.js";
import type * as _taskWorkflow_staleness from "../_taskWorkflow/staleness.js";
import type * as _taskWorkflow_uiImplementationPrompt from "../_taskWorkflow/uiImplementationPrompt.js";
import type * as _taskWorkflow_urls from "../_taskWorkflow/urls.js";
import type * as _taskWorkflow_usageLimitReset from "../_taskWorkflow/usageLimitReset.js";
import type * as _taskWorkflow_watchdog from "../_taskWorkflow/watchdog.js";
import type * as _taskWorkflow_workflowDefinition from "../_taskWorkflow/workflowDefinition.js";
import type * as _usageLimits_claudeUsage from "../_usageLimits/claudeUsage.js";
import type * as _usageLimits_rows from "../_usageLimits/rows.js";
import type * as _userProviderAccounts_credentialSource from "../_userProviderAccounts/credentialSource.js";
import type * as _userProviderAccounts_defaults from "../_userProviderAccounts/defaults.js";
import type * as _userProviderAccounts_listing from "../_userProviderAccounts/listing.js";
import type * as _userProviderAccounts_sharing from "../_userProviderAccounts/sharing.js";
import type * as _users_directory from "../_users/directory.js";
import type * as _users_lastSeen from "../_users/lastSeen.js";
import type * as _validators_aiModels from "../_validators/aiModels.js";
import type * as _validators_enums from "../_validators/enums.js";
import type * as _validators_personalisation from "../_validators/personalisation.js";
import type * as _validators_shapes from "../_validators/shapes.js";
import type * as _validators_shortcuts from "../_validators/shortcuts.js";
import type * as _validators_tableFields from "../_validators/tableFields.js";
import type * as agentRuns from "../agentRuns.js";
import type * as agentTaskChatWorkflow from "../agentTaskChatWorkflow.js";
import type * as agentTasks from "../agentTasks.js";
import type * as analytics from "../analytics.js";
import type * as annotations from "../annotations.js";
import type * as appTabSlug from "../appTabSlug.js";
import type * as appTabs from "../appTabs.js";
import type * as artifacts from "../artifacts.js";
import type * as auth from "../auth.js";
import type * as automationEmail from "../automationEmail.js";
import type * as automationWorkflow from "../automationWorkflow.js";
import type * as automations from "../automations.js";
import type * as backgroundProcesses from "../backgroundProcesses.js";
import type * as buildWorkflow from "../buildWorkflow.js";
import type * as changelog from "../changelog.js";
import type * as cronManager from "../cronManager.js";
import type * as crons from "../crons.js";
import type * as dataMigrations from "../dataMigrations.js";
import type * as docComments from "../docComments.js";
import type * as docInterviewWorkflow from "../docInterviewWorkflow.js";
import type * as docSubscribers from "../docSubscribers.js";
import type * as docVersions from "../docVersions.js";
import type * as docs from "../docs.js";
import type * as drafts from "../drafts.js";
import type * as email from "../email.js";
import type * as emailTemplates from "../emailTemplates.js";
import type * as encryption from "../encryption.js";
import type * as envVarResolver from "../envVarResolver.js";
import type * as evaluationReports from "../evaluationReports.js";
import type * as evaluationWorkflow from "../evaluationWorkflow.js";
import type * as extensionReleases from "../extensionReleases.js";
import type * as fixEnvVars from "../fixEnvVars.js";
import type * as functions from "../functions.js";
import type * as github from "../github.js";
import type * as githubAuth from "../githubAuth.js";
import type * as githubPrivateKeyFormat from "../githubPrivateKeyFormat.js";
import type * as githubRepos from "../githubRepos.js";
import type * as githubUserAuth from "../githubUserAuth.js";
import type * as githubWebhook from "../githubWebhook.js";
import type * as harnessSkills from "../harnessSkills.js";
import type * as http from "../http.js";
import type * as legacyIds from "../legacyIds.js";
import type * as linearActions from "../linearActions.js";
import type * as logs from "../logs.js";
import type * as mcp_browserLock from "../mcp/browserLock.js";
import type * as mcp_convexQueryLimits from "../mcp/convexQueryLimits.js";
import type * as mcp_entityRef from "../mcp/entityRef.js";
import type * as mcp_entityTools from "../mcp/entityTools.js";
import type * as mcp_media from "../mcp/media.js";
import type * as mcp_native from "../mcp/native.js";
import type * as mcp_nodeActions from "../mcp/nodeActions.js";
import type * as mcp_oauth from "../mcp/oauth.js";
import type * as mcp_orchestratorDelivery from "../mcp/orchestratorDelivery.js";
import type * as mcp_orchestratorTools from "../mcp/orchestratorTools.js";
import type * as mcp_postgres from "../mcp/postgres.js";
import type * as mcp_queries from "../mcp/queries.js";
import type * as mcp_routes from "../mcp/routes.js";
import type * as mcp_sessionRef from "../mcp/sessionRef.js";
import type * as mcp_supabase from "../mcp/supabase.js";
import type * as mcp_toolShared from "../mcp/toolShared.js";
import type * as mcp_tools from "../mcp/tools.js";
import type * as mentions from "../mentions.js";
import type * as messages from "../messages.js";
import type * as migrations from "../migrations.js";
import type * as notificationDigest from "../notificationDigest.js";
import type * as notificationEmail from "../notificationEmail.js";
import type * as notifications from "../notifications.js";
import type * as numId from "../numId.js";
import type * as orchestratorNotify from "../orchestratorNotify.js";
import type * as orchestratorShared from "../orchestratorShared.js";
import type * as orchestratorWatch from "../orchestratorWatch.js";
import type * as pendingQuestions from "../pendingQuestions.js";
import type * as prBody from "../prBody.js";
import type * as prRecapWorkflow from "../prRecapWorkflow.js";
import type * as presence from "../presence.js";
import type * as previewGrant from "../previewGrant.js";
import type * as previewGrantConfig from "../previewGrantConfig.js";
import type * as projectChatWorkflow from "../projectChatWorkflow.js";
import type * as projectInterviewWorkflow from "../projectInterviewWorkflow.js";
import type * as projectSandboxWorkflow from "../projectSandboxWorkflow.js";
import type * as projects from "../projects.js";
import type * as promptStash from "../promptStash.js";
import type * as prompts_doc from "../prompts/doc.js";
import type * as prompts_index from "../prompts/index.js";
import type * as prompts_project from "../prompts/project.js";
import type * as prompts_shared from "../prompts/shared.js";
import type * as proposedPlans from "../proposedPlans.js";
import type * as prosemirrorSync from "../prosemirrorSync.js";
import type * as pty from "../pty.js";
import type * as queuedMessages from "../queuedMessages.js";
import type * as repoEnvVars from "../repoEnvVars.js";
import type * as repoEnvVarsActions from "../repoEnvVarsActions.js";
import type * as repoSkills from "../repoSkills.js";
import type * as repoSnapshots from "../repoSnapshots.js";
import type * as repoSystemSkills from "../repoSystemSkills.js";
import type * as repoUtils from "../repoUtils.js";
import type * as sandbox from "../sandbox.js";
import type * as sandboxAuthConfig from "../sandboxAuthConfig.js";
import type * as sandboxAutoStop from "../sandboxAutoStop.js";
import type * as sandboxCleanup from "../sandboxCleanup.js";
import type * as sandboxConfigFiles from "../sandboxConfigFiles.js";
import type * as sandboxDaemon from "../sandboxDaemon.js";
import type * as sandboxGitCredentials from "../sandboxGitCredentials.js";
import type * as sandboxHeal from "../sandboxHeal.js";
import type * as sandboxJwt from "../sandboxJwt.js";
import type * as sandboxPanes from "../sandboxPanes.js";
import type * as screenshots from "../screenshots.js";
import type * as sessionWorkflow from "../sessionWorkflow.js";
import type * as sessions from "../sessions.js";
import type * as snapshotActions from "../snapshotActions.js";
import type * as snapshotWorkflow from "../snapshotWorkflow.js";
import type * as spotlight from "../spotlight.js";
import type * as streaming from "../streaming.js";
import type * as summarizeWorkflow from "../summarizeWorkflow.js";
import type * as syncSettings from "../syncSettings.js";
import type * as taskActivity from "../taskActivity.js";
import type * as taskActivityCoalesce from "../taskActivityCoalesce.js";
import type * as taskComments from "../taskComments.js";
import type * as taskDependencies from "../taskDependencies.js";
import type * as taskReactions from "../taskReactions.js";
import type * as taskSandboxEvents from "../taskSandboxEvents.js";
import type * as taskSandboxWorkflow from "../taskSandboxWorkflow.js";
import type * as taskSubscribers from "../taskSubscribers.js";
import type * as taskWorkflow from "../taskWorkflow.js";
import type * as taskWorkflowActions from "../taskWorkflowActions.js";
import type * as teamEnvVars from "../teamEnvVars.js";
import type * as teamEnvVarsActions from "../teamEnvVarsActions.js";
import type * as teamMembers from "../teamMembers.js";
import type * as teams from "../teams.js";
import type * as testGenWorkflow from "../testGenWorkflow.js";
import type * as textGen from "../textGen.js";
import type * as today from "../today.js";
import type * as transcription from "../transcription.js";
import type * as turns from "../turns.js";
import type * as usage from "../usage.js";
import type * as usageLimits from "../usageLimits.js";
import type * as usageLimitsActions from "../usageLimitsActions.js";
import type * as userProviderAccounts from "../userProviderAccounts.js";
import type * as userProviderAccountsActions from "../userProviderAccountsActions.js";
import type * as users from "../users.js";
import type * as validators from "../validators.js";
import type * as workflowManager from "../workflowManager.js";
import type * as workflowWatchdog from "../workflowWatchdog.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "_agentRuns/mutations": typeof _agentRuns_mutations;
  "_agentRuns/queries": typeof _agentRuns_queries;
  "_agentTasks/chatPrompt": typeof _agentTasks_chatPrompt;
  "_agentTasks/drafts": typeof _agentTasks_drafts;
  "_agentTasks/execution": typeof _agentTasks_execution;
  "_agentTasks/helpers": typeof _agentTasks_helpers;
  "_agentTasks/internal": typeof _agentTasks_internal;
  "_agentTasks/mutations": typeof _agentTasks_mutations;
  "_agentTasks/queries": typeof _agentTasks_queries;
  "_agentTasks/runSummary": typeof _agentTasks_runSummary;
  "_agentTasks/sandbox": typeof _agentTasks_sandbox;
  "_auth/currentUser": typeof _auth_currentUser;
  "_auth/experimentalFlags": typeof _auth_experimentalFlags;
  "_automationWorkflow/deliverable": typeof _automationWorkflow_deliverable;
  "_automationWorkflow/findings": typeof _automationWorkflow_findings;
  "_automationWorkflow/prompts": typeof _automationWorkflow_prompts;
  "_automations/crud": typeof _automations_crud;
  "_automations/findings": typeof _automations_findings;
  "_automations/helpers": typeof _automations_helpers;
  "_automations/prompts/addTestCoverage": typeof _automations_prompts_addTestCoverage;
  "_automations/prompts/dailyStandup": typeof _automations_prompts_dailyStandup;
  "_automations/prompts/findCriticalBugs": typeof _automations_prompts_findCriticalBugs;
  "_automations/prompts/generateDocs": typeof _automations_prompts_generateDocs;
  "_automations/prompts/improveCodeStructure": typeof _automations_prompts_improveCodeStructure;
  "_automations/prompts/thermoNuclearCodeReview": typeof _automations_prompts_thermoNuclearCodeReview;
  "_automations/runs": typeof _automations_runs;
  "_automations/systemAutomations": typeof _automations_systemAutomations;
  "_automations/systemInstall": typeof _automations_systemInstall;
  "_automations/triggers": typeof _automations_triggers;
  "_chat/cancelledMessage": typeof _chat_cancelledMessage;
  "_chat/chatResult": typeof _chat_chatResult;
  "_chat/daemonClaimPause": typeof _chat_daemonClaimPause;
  "_chat/pendingTurnRestage": typeof _chat_pendingTurnRestage;
  "_chat/projectChatDaemon": typeof _chat_projectChatDaemon;
  "_chat/stallRetry": typeof _chat_stallRetry;
  "_chat/stallWatchdog": typeof _chat_stallWatchdog;
  "_chat/storageUrls": typeof _chat_storageUrls;
  "_chat/surfaceAdapters": typeof _chat_surfaceAdapters;
  "_chat/taskChatDaemon": typeof _chat_taskChatDaemon;
  "_chat/turnLease": typeof _chat_turnLease;
  "_chat/turnProjection": typeof _chat_turnProjection;
  "_chat/turnStore": typeof _chat_turnStore;
  "_deployment/vercel": typeof _deployment_vercel;
  "_docEditor/markdown": typeof _docEditor_markdown;
  "_drafts/helpers": typeof _drafts_helpers;
  "_drafts/mutations": typeof _drafts_mutations;
  "_drafts/queries": typeof _drafts_queries;
  "_env/publicConvexUrls": typeof _env_publicConvexUrls;
  "_envVars/listDisplay": typeof _envVars_listDisplay;
  "_envVars/vercelCredentials": typeof _envVars_vercelCredentials;
  "_git/branchNames": typeof _git_branchNames;
  "_git/remoteRef": typeof _git_remoteRef;
  "_github/api": typeof _github_api;
  "_github/authErrors": typeof _github_authErrors;
  "_github/deploymentSnapshot": typeof _github_deploymentSnapshot;
  "_github/evaPrOwnership": typeof _github_evaPrOwnership;
  "_github/helpers": typeof _github_helpers;
  "_github/prComments": typeof _github_prComments;
  "_github/prDescription": typeof _github_prDescription;
  "_github/prDescriptionPrompt": typeof _github_prDescriptionPrompt;
  "_github/prDiff": typeof _github_prDiff;
  "_github/prDiffFallback": typeof _github_prDiffFallback;
  "_github/prErrors": typeof _github_prErrors;
  "_github/prFlow": typeof _github_prFlow;
  "_github/prMeta": typeof _github_prMeta;
  "_github/prOverview": typeof _github_prOverview;
  "_github/prRecapService": typeof _github_prRecapService;
  "_github/prReview": typeof _github_prReview;
  "_github/prTitleSync": typeof _github_prTitleSync;
  "_github/pullRequests": typeof _github_pullRequests;
  "_github/sessionMergeGuard": typeof _github_sessionMergeGuard;
  "_github/sync": typeof _github_sync;
  "_github/userAuth": typeof _github_userAuth;
  "_github/userTokens": typeof _github_userTokens;
  "_githubRepos/helpers": typeof _githubRepos_helpers;
  "_githubRepos/mutations": typeof _githubRepos_mutations;
  "_githubRepos/queries": typeof _githubRepos_queries;
  "_githubRepos/sandboxRepoPick": typeof _githubRepos_sandboxRepoPick;
  "_githubRepos/sync": typeof _githubRepos_sync;
  "_harnessSkills/filter": typeof _harnessSkills_filter;
  "_harnessSkills/report": typeof _harnessSkills_report;
  "_logs/resolveProjectId": typeof _logs_resolveProjectId;
  "_logs/usage": typeof _logs_usage;
  "_logs/usageSummary": typeof _logs_usageSummary;
  "_mcp/redirectUri": typeof _mcp_redirectUri;
  "_mentions/dataKinds": typeof _mentions_dataKinds;
  "_mentions/extractMentionedUserIds": typeof _mentions_extractMentionedUserIds;
  "_mentions/listData": typeof _mentions_listData;
  "_mentions/mentionToken": typeof _mentions_mentionToken;
  "_mentions/notifyChatMentions": typeof _mentions_notifyChatMentions;
  "_mentions/resolveDocMentions": typeof _mentions_resolveDocMentions;
  "_mentions/resolveMessageTokens": typeof _mentions_resolveMessageTokens;
  "_mentions/resolveSkillMentions": typeof _mentions_resolveSkillMentions;
  "_mentions/skillToken": typeof _mentions_skillToken;
  "_messages/media": typeof _messages_media;
  "_messages/preview": typeof _messages_preview;
  "_migrations/backfillArchivedFromPrState": typeof _migrations_backfillArchivedFromPrState;
  "_migrations/backfillEvaPrRecapOrigin": typeof _migrations_backfillEvaPrRecapOrigin;
  "_migrations/backfillExperimentalFlags": typeof _migrations_backfillExperimentalFlags;
  "_migrations/backfillNumIds": typeof _migrations_backfillNumIds;
  "_migrations/backfillQueuedMessageOrder": typeof _migrations_backfillQueuedMessageOrder;
  "_migrations/backfillTaskSubscribers": typeof _migrations_backfillTaskSubscribers;
  "_migrations/cleanup": typeof _migrations_cleanup;
  "_migrations/deleteRepos": typeof _migrations_deleteRepos;
  "_migrations/deploymentUrl": typeof _migrations_deploymentUrl;
  "_migrations/excludeConvexUrlFromSandbox": typeof _migrations_excludeConvexUrlFromSandbox;
  "_migrations/logProjectIds": typeof _migrations_logProjectIds;
  "_migrations/projectInterview": typeof _migrations_projectInterview;
  "_migrations/projectPhases": typeof _migrations_projectPhases;
  "_migrations/removeProjectIdField": typeof _migrations_removeProjectIdField;
  "_migrations/removeSessionStartupRequestedAt": typeof _migrations_removeSessionStartupRequestedAt;
  "_migrations/removeSnapshotWarmupFields": typeof _migrations_removeSnapshotWarmupFields;
  "_migrations/repoSkills": typeof _migrations_repoSkills;
  "_prRecapWorkflow/finalizeOutcome": typeof _prRecapWorkflow_finalizeOutcome;
  "_prRecapWorkflow/prompts": typeof _prRecapWorkflow_prompts;
  "_prRecapWorkflow/recapState": typeof _prRecapWorkflow_recapState;
  "_prRecapWorkflow/staleDoc": typeof _prRecapWorkflow_staleDoc;
  "_prRecapWorkflow/start": typeof _prRecapWorkflow_start;
  "_projects/chatPrompt": typeof _projects_chatPrompt;
  "_projects/development": typeof _projects_development;
  "_projects/helpers": typeof _projects_helpers;
  "_projects/internal": typeof _projects_internal;
  "_projects/mutations": typeof _projects_mutations;
  "_projects/prSync": typeof _projects_prSync;
  "_projects/queries": typeof _projects_queries;
  "_projects/sandbox": typeof _projects_sandbox;
  "_pty/launchDevServerInVercelConsole": typeof _pty_launchDevServerInVercelConsole;
  "_pty/owners": typeof _pty_owners;
  "_pty/vercel": typeof _pty_vercel;
  "_queues/helpers": typeof _queues_helpers;
  "_repoSkills/content": typeof _repoSkills_content;
  "_repoSkills/decodeGitHubContent": typeof _repoSkills_decodeGitHubContent;
  "_repoSkills/skillMarkdown": typeof _repoSkills_skillMarkdown;
  "_repoSkills/sync": typeof _repoSkills_sync;
  "_repoSnapshots/builds": typeof _repoSnapshots_builds;
  "_repoSnapshots/config": typeof _repoSnapshots_config;
  "_repoSnapshots/repoMetadata": typeof _repoSnapshots_repoMetadata;
  "_repoSnapshots/sanitizeSeededApps": typeof _repoSnapshots_sanitizeSeededApps;
  "_sandbox/factory": typeof _sandbox_factory;
  "_sandbox/ffmpegInstall": typeof _sandbox_ffmpegInstall;
  "_sandbox/owner": typeof _sandbox_owner;
  "_sandbox/provider": typeof _sandbox_provider;
  "_sandbox/resolveExistingSandboxId": typeof _sandbox_resolveExistingSandboxId;
  "_sandbox/startupActivity": typeof _sandbox_startupActivity;
  "_sandbox/stickyPreview": typeof _sandbox_stickyPreview;
  "_sandbox/stopRecovery": typeof _sandbox_stopRecovery;
  "_sandbox/tags": typeof _sandbox_tags;
  "_sandbox/vercelEnvFile": typeof _sandbox_vercelEnvFile;
  "_sandbox/vercelProvider": typeof _sandbox_vercelProvider;
  "_sandbox/vercelSnapshotOptions": typeof _sandbox_vercelSnapshotOptions;
  "_sandbox_runtime/attachments": typeof _sandbox_runtime_attachments;
  "_sandbox_runtime/backgroundProcesses": typeof _sandbox_runtime_backgroundProcesses;
  "_sandbox_runtime/bulkSnapshotRetention": typeof _sandbox_runtime_bulkSnapshotRetention;
  "_sandbox_runtime/callbackAuth": typeof _sandbox_runtime_callbackAuth;
  "_sandbox_runtime/callbackScript": typeof _sandbox_runtime_callbackScript;
  "_sandbox_runtime/callbackScriptFingerprint": typeof _sandbox_runtime_callbackScriptFingerprint;
  "_sandbox_runtime/claudeCliVersion": typeof _sandbox_runtime_claudeCliVersion;
  "_sandbox_runtime/convexLocalBackend": typeof _sandbox_runtime_convexLocalBackend;
  "_sandbox_runtime/daemonEntitySnapshot": typeof _sandbox_runtime_daemonEntitySnapshot;
  "_sandbox_runtime/daemonPaths": typeof _sandbox_runtime_daemonPaths;
  "_sandbox_runtime/desktop": typeof _sandbox_runtime_desktop;
  "_sandbox_runtime/devServer": typeof _sandbox_runtime_devServer;
  "_sandbox_runtime/divergedPublish": typeof _sandbox_runtime_divergedPublish;
  "_sandbox_runtime/execution": typeof _sandbox_runtime_execution;
  "_sandbox_runtime/git": typeof _sandbox_runtime_git;
  "_sandbox_runtime/gitCredentials": typeof _sandbox_runtime_gitCredentials;
  "_sandbox_runtime/gitRemoteCommand": typeof _sandbox_runtime_gitRemoteCommand;
  "_sandbox_runtime/helpers": typeof _sandbox_runtime_helpers;
  "_sandbox_runtime/httpReadyProbe": typeof _sandbox_runtime_httpReadyProbe;
  "_sandbox_runtime/launch": typeof _sandbox_runtime_launch;
  "_sandbox_runtime/lifecycle": typeof _sandbox_runtime_lifecycle;
  "_sandbox_runtime/prepareSandboxSteps": typeof _sandbox_runtime_prepareSandboxSteps;
  "_sandbox_runtime/previewProxy": typeof _sandbox_runtime_previewProxy;
  "_sandbox_runtime/previewRecovery": typeof _sandbox_runtime_previewRecovery;
  "_sandbox_runtime/resumeSandboxSteps": typeof _sandbox_runtime_resumeSandboxSteps;
  "_sandbox_runtime/runDevServer": typeof _sandbox_runtime_runDevServer;
  "_sandbox_runtime/sandboxErrors": typeof _sandbox_runtime_sandboxErrors;
  "_sandbox_runtime/sandboxFiles": typeof _sandbox_runtime_sandboxFiles;
  "_sandbox_runtime/services": typeof _sandbox_runtime_services;
  "_sandbox_runtime/sessions": typeof _sandbox_runtime_sessions;
  "_sandbox_runtime/snapshotStates": typeof _sandbox_runtime_snapshotStates;
  "_sandbox_runtime/swap": typeof _sandbox_runtime_swap;
  "_sandbox_runtime/turnRevert": typeof _sandbox_runtime_turnRevert;
  "_sandbox_runtime/vercelAppPorts": typeof _sandbox_runtime_vercelAppPorts;
  "_sessions/backgroundAgents": typeof _sessions_backgroundAgents;
  "_sessions/baseBranch": typeof _sessions_baseBranch;
  "_sessions/daemonState": typeof _sessions_daemonState;
  "_sessions/execution": typeof _sessions_execution;
  "_sessions/helpers": typeof _sessions_helpers;
  "_sessions/internal": typeof _sessions_internal;
  "_sessions/mutations": typeof _sessions_mutations;
  "_sessions/orchestrator": typeof _sessions_orchestrator;
  "_sessions/pendingTurnRecovery": typeof _sessions_pendingTurnRecovery;
  "_sessions/prArchive": typeof _sessions_prArchive;
  "_sessions/prompts": typeof _sessions_prompts;
  "_sessions/proposedPlans": typeof _sessions_proposedPlans;
  "_sessions/pty": typeof _sessions_pty;
  "_sessions/queries": typeof _sessions_queries;
  "_sessions/resultTarget": typeof _sessions_resultTarget;
  "_sessions/sandbox": typeof _sessions_sandbox;
  "_sessions/workflow": typeof _sessions_workflow;
  "_shared/commentAnchor": typeof _shared_commentAnchor;
  "_shared/modelHandoff": typeof _shared_modelHandoff;
  "_systemSkills/evaAsk": typeof _systemSkills_evaAsk;
  "_systemSkills/evaAudit": typeof _systemSkills_evaAudit;
  "_systemSkills/evaCapture": typeof _systemSkills_evaCapture;
  "_systemSkills/evaDesign": typeof _systemSkills_evaDesign;
  "_systemSkills/evaOrchestrator": typeof _systemSkills_evaOrchestrator;
  "_systemSkills/evaPlan": typeof _systemSkills_evaPlan;
  "_systemSkills/registry": typeof _systemSkills_registry;
  "_taskWorkflow/deploymentHelpers": typeof _taskWorkflow_deploymentHelpers;
  "_taskWorkflow/events": typeof _taskWorkflow_events;
  "_taskWorkflow/helpers": typeof _taskWorkflow_helpers;
  "_taskWorkflow/livenessProbe": typeof _taskWorkflow_livenessProbe;
  "_taskWorkflow/prompts": typeof _taskWorkflow_prompts;
  "_taskWorkflow/publicMutations": typeof _taskWorkflow_publicMutations;
  "_taskWorkflow/queries": typeof _taskWorkflow_queries;
  "_taskWorkflow/recovery": typeof _taskWorkflow_recovery;
  "_taskWorkflow/resolveBaseBranch": typeof _taskWorkflow_resolveBaseBranch;
  "_taskWorkflow/runLifecycle": typeof _taskWorkflow_runLifecycle;
  "_taskWorkflow/scheduling": typeof _taskWorkflow_scheduling;
  "_taskWorkflow/staleness": typeof _taskWorkflow_staleness;
  "_taskWorkflow/uiImplementationPrompt": typeof _taskWorkflow_uiImplementationPrompt;
  "_taskWorkflow/urls": typeof _taskWorkflow_urls;
  "_taskWorkflow/usageLimitReset": typeof _taskWorkflow_usageLimitReset;
  "_taskWorkflow/watchdog": typeof _taskWorkflow_watchdog;
  "_taskWorkflow/workflowDefinition": typeof _taskWorkflow_workflowDefinition;
  "_usageLimits/claudeUsage": typeof _usageLimits_claudeUsage;
  "_usageLimits/rows": typeof _usageLimits_rows;
  "_userProviderAccounts/credentialSource": typeof _userProviderAccounts_credentialSource;
  "_userProviderAccounts/defaults": typeof _userProviderAccounts_defaults;
  "_userProviderAccounts/listing": typeof _userProviderAccounts_listing;
  "_userProviderAccounts/sharing": typeof _userProviderAccounts_sharing;
  "_users/directory": typeof _users_directory;
  "_users/lastSeen": typeof _users_lastSeen;
  "_validators/aiModels": typeof _validators_aiModels;
  "_validators/enums": typeof _validators_enums;
  "_validators/personalisation": typeof _validators_personalisation;
  "_validators/shapes": typeof _validators_shapes;
  "_validators/shortcuts": typeof _validators_shortcuts;
  "_validators/tableFields": typeof _validators_tableFields;
  agentRuns: typeof agentRuns;
  agentTaskChatWorkflow: typeof agentTaskChatWorkflow;
  agentTasks: typeof agentTasks;
  analytics: typeof analytics;
  annotations: typeof annotations;
  appTabSlug: typeof appTabSlug;
  appTabs: typeof appTabs;
  artifacts: typeof artifacts;
  auth: typeof auth;
  automationEmail: typeof automationEmail;
  automationWorkflow: typeof automationWorkflow;
  automations: typeof automations;
  backgroundProcesses: typeof backgroundProcesses;
  buildWorkflow: typeof buildWorkflow;
  changelog: typeof changelog;
  cronManager: typeof cronManager;
  crons: typeof crons;
  dataMigrations: typeof dataMigrations;
  docComments: typeof docComments;
  docInterviewWorkflow: typeof docInterviewWorkflow;
  docSubscribers: typeof docSubscribers;
  docVersions: typeof docVersions;
  docs: typeof docs;
  drafts: typeof drafts;
  email: typeof email;
  emailTemplates: typeof emailTemplates;
  encryption: typeof encryption;
  envVarResolver: typeof envVarResolver;
  evaluationReports: typeof evaluationReports;
  evaluationWorkflow: typeof evaluationWorkflow;
  extensionReleases: typeof extensionReleases;
  fixEnvVars: typeof fixEnvVars;
  functions: typeof functions;
  github: typeof github;
  githubAuth: typeof githubAuth;
  githubPrivateKeyFormat: typeof githubPrivateKeyFormat;
  githubRepos: typeof githubRepos;
  githubUserAuth: typeof githubUserAuth;
  githubWebhook: typeof githubWebhook;
  harnessSkills: typeof harnessSkills;
  http: typeof http;
  legacyIds: typeof legacyIds;
  linearActions: typeof linearActions;
  logs: typeof logs;
  "mcp/browserLock": typeof mcp_browserLock;
  "mcp/convexQueryLimits": typeof mcp_convexQueryLimits;
  "mcp/entityRef": typeof mcp_entityRef;
  "mcp/entityTools": typeof mcp_entityTools;
  "mcp/media": typeof mcp_media;
  "mcp/native": typeof mcp_native;
  "mcp/nodeActions": typeof mcp_nodeActions;
  "mcp/oauth": typeof mcp_oauth;
  "mcp/orchestratorDelivery": typeof mcp_orchestratorDelivery;
  "mcp/orchestratorTools": typeof mcp_orchestratorTools;
  "mcp/postgres": typeof mcp_postgres;
  "mcp/queries": typeof mcp_queries;
  "mcp/routes": typeof mcp_routes;
  "mcp/sessionRef": typeof mcp_sessionRef;
  "mcp/supabase": typeof mcp_supabase;
  "mcp/toolShared": typeof mcp_toolShared;
  "mcp/tools": typeof mcp_tools;
  mentions: typeof mentions;
  messages: typeof messages;
  migrations: typeof migrations;
  notificationDigest: typeof notificationDigest;
  notificationEmail: typeof notificationEmail;
  notifications: typeof notifications;
  numId: typeof numId;
  orchestratorNotify: typeof orchestratorNotify;
  orchestratorShared: typeof orchestratorShared;
  orchestratorWatch: typeof orchestratorWatch;
  pendingQuestions: typeof pendingQuestions;
  prBody: typeof prBody;
  prRecapWorkflow: typeof prRecapWorkflow;
  presence: typeof presence;
  previewGrant: typeof previewGrant;
  previewGrantConfig: typeof previewGrantConfig;
  projectChatWorkflow: typeof projectChatWorkflow;
  projectInterviewWorkflow: typeof projectInterviewWorkflow;
  projectSandboxWorkflow: typeof projectSandboxWorkflow;
  projects: typeof projects;
  promptStash: typeof promptStash;
  "prompts/doc": typeof prompts_doc;
  "prompts/index": typeof prompts_index;
  "prompts/project": typeof prompts_project;
  "prompts/shared": typeof prompts_shared;
  proposedPlans: typeof proposedPlans;
  prosemirrorSync: typeof prosemirrorSync;
  pty: typeof pty;
  queuedMessages: typeof queuedMessages;
  repoEnvVars: typeof repoEnvVars;
  repoEnvVarsActions: typeof repoEnvVarsActions;
  repoSkills: typeof repoSkills;
  repoSnapshots: typeof repoSnapshots;
  repoSystemSkills: typeof repoSystemSkills;
  repoUtils: typeof repoUtils;
  sandbox: typeof sandbox;
  sandboxAuthConfig: typeof sandboxAuthConfig;
  sandboxAutoStop: typeof sandboxAutoStop;
  sandboxCleanup: typeof sandboxCleanup;
  sandboxConfigFiles: typeof sandboxConfigFiles;
  sandboxDaemon: typeof sandboxDaemon;
  sandboxGitCredentials: typeof sandboxGitCredentials;
  sandboxHeal: typeof sandboxHeal;
  sandboxJwt: typeof sandboxJwt;
  sandboxPanes: typeof sandboxPanes;
  screenshots: typeof screenshots;
  sessionWorkflow: typeof sessionWorkflow;
  sessions: typeof sessions;
  snapshotActions: typeof snapshotActions;
  snapshotWorkflow: typeof snapshotWorkflow;
  spotlight: typeof spotlight;
  streaming: typeof streaming;
  summarizeWorkflow: typeof summarizeWorkflow;
  syncSettings: typeof syncSettings;
  taskActivity: typeof taskActivity;
  taskActivityCoalesce: typeof taskActivityCoalesce;
  taskComments: typeof taskComments;
  taskDependencies: typeof taskDependencies;
  taskReactions: typeof taskReactions;
  taskSandboxEvents: typeof taskSandboxEvents;
  taskSandboxWorkflow: typeof taskSandboxWorkflow;
  taskSubscribers: typeof taskSubscribers;
  taskWorkflow: typeof taskWorkflow;
  taskWorkflowActions: typeof taskWorkflowActions;
  teamEnvVars: typeof teamEnvVars;
  teamEnvVarsActions: typeof teamEnvVarsActions;
  teamMembers: typeof teamMembers;
  teams: typeof teams;
  testGenWorkflow: typeof testGenWorkflow;
  textGen: typeof textGen;
  today: typeof today;
  transcription: typeof transcription;
  turns: typeof turns;
  usage: typeof usage;
  usageLimits: typeof usageLimits;
  usageLimitsActions: typeof usageLimitsActions;
  userProviderAccounts: typeof userProviderAccounts;
  userProviderAccountsActions: typeof userProviderAccountsActions;
  users: typeof users;
  validators: typeof validators;
  workflowManager: typeof workflowManager;
  workflowWatchdog: typeof workflowWatchdog;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  presence: import("@convex-dev/presence/_generated/component.js").ComponentApi<"presence">;
  prosemirrorSync: import("@convex-dev/prosemirror-sync/_generated/component.js").ComponentApi<"prosemirrorSync">;
  workflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;
  crons: import("@convex-dev/crons/_generated/component.js").ComponentApi<"crons">;
  actionCache: import("@convex-dev/action-cache/_generated/component.js").ComponentApi<"actionCache">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
};
